[package]
name = "resync"
version = "0.10.0"
edition = "2024"
rust-version = "1.98.0"
workspace = "testing/util"
authors = ["Ivan Chetchasov <vi.is.chapmann@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A LEGO-like synchronization primitives library for Rust"
repository = "https://github.com/vi-is-ramen/resync"
readme = "README.md"
homepage = "https://github.com/vi-is-ramen/resync"
categories = ["concurrency", "no-std", "os"]
keywords = ["mutex", "spinlock", "synchronization", "no_std", "lock"]

[dependencies]
libc = { version = "0.2", optional = true }
# lock_api = "0.4"
windows-sys = { version = "0.61", optional = true, features = [
    "Win32_System_Threading",
    "Win32_Foundation"
] }

[build-dependencies]
rustversion = "1"

# [dev-dependencies]
# criterion = "0.8"

[features]
default = [ "std" ]
std = [ "dep:libc", "dep:windows-sys" ]
fake = []
dev = []
__lint = [ "std", "fake", "dev" ]

[lints.rust]
unexpected_cfgs = { level = 'allow', check-cfg = ['cfg(nightly)', 'cfg(stable)', 'cfg(beta)', 'cfg(dev)'] }
missing_docs = 'deny'
missing_debug_implementations = 'deny'

# [[bench]]
# name = "mutex"
# harness = false
# required-features = []

# [[bench]]
# name = "rwlock"
# harness = false
# required-features = []

# [[bench]]
# name = "barrier"
# harness = false
# required-features = []
