[book]
authors = ["Ivan Chetchasov <vi.is.chapmann@gmail.com>"]
language = "en"
src = "src"
title = "Resync's Developer Guide"

[output.html]
git-repository-url = "https://github.com/vi-is-ramen/resync/"
edit-url-template = "https://github.com/vi-is-ramen/resync/edit/main/{path}"
site-url = "/resync/dev/"

[output.html.playground]
editable = true
